// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuyNo8PA8b4np9YCk7UpkcIqGQ6eWxqzs',
    appId: '1:32114158674:web:d01af726ad8a45b526838b',
    messagingSenderId: '32114158674',
    projectId: 'expensemanager-49745',
    authDomain: 'expensemanager-49745.firebaseapp.com',
    storageBucket: 'expensemanager-49745.firebasestorage.app',
    measurementId: 'G-GK54MYNQ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcHmSXWN0Xvyn1EDnqNnTig_njG0Lack',
    appId: '1:32114158674:android:3eee93b13eac27cf26838b',
    messagingSenderId: '32114158674',
    projectId: 'expensemanager-49745',
    storageBucket: 'expensemanager-49745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxcbz_BJx4qbs0mDJkOebeobadbUmaRo',
    appId: '1:32114158674:ios:b435638b2ae168c026838b',
    messagingSenderId: '32114158674',
    projectId: 'expensemanager-49745',
    storageBucket: 'expensemanager-49745.firebasestorage.app',
    iosBundleId: 'com.example.exzplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxcbz_BJx4qbs0mDJkOebeobadbUmaRo',
    appId: '1:32114158674:ios:b435638b2ae168c026838b',
    messagingSenderId: '32114158674',
    projectId: 'expensemanager-49745',
    storageBucket: 'expensemanager-49745.firebasestorage.app',
    iosBundleId: 'com.example.exzplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuyNo8PA8b4np9YCk7UpkcIqGQ6eWxqzs',
    appId: '1:32114158674:web:fbfef31df857e38726838b',
    messagingSenderId: '32114158674',
    projectId: 'expensemanager-49745',
    authDomain: 'expensemanager-49745.firebaseapp.com',
    storageBucket: 'expensemanager-49745.firebasestorage.app',
    measurementId: 'G-FY3HDSKVRB',
  );
}
